#! /bin/bash
PATH_SSH=/home/$SUDO_USER/.ssh/id_rsa
echo $SUDO_USER > /etc/dropbox-username.txt
chmod 666 "/etc/dropbox-username.txt"
if [ ! -f $PATH_SSH ]; then
	echo "Creating ssh key..."
	(echo $PATH_SSH;echo;echo)|sudo -u $SUDO_USER ssh-keygen -t rsa
fi
cd "Source Code"
gcc -pthread -o dropbox-inotify main_process.c inotify.c wrapper.c
cp "./dropbox-inotify" "/usr/bin/"
cd ..
chmod +x "./dbconfig"
chmod +x "./dbstatus"
chmod +x "./dropbox-start"
cp "./dbconfig" "/usr/bin/"
cp "./dbstatus" "/usr/bin/"
cp "./dropbox-start" "/usr/bin/"
cp ."/dbox" "/etc/init.d"
touch "/etc/dropbox.conf"
chmod 666 "/etc/dropbox.conf"
chmod 755 "/etc/init.d/dbox"
echo "Software installed!"
systemctl enable dbox.service
systemctl enable sshd.service
